### ISSUE TITLE
Google Chrome 開發人員工具

### ISSUE THREAD

**Issue by yulinyeh** [f2etw/book#8]
# Google Chrome 開發人員工具

隨著 Google Chrome 版本的更新，現在開發也越來越依賴開發者工具。  
因為不管是微調樣式，或是偵錯 JavaScript 都很方便，真的是咻一下就把問題解決了。

接下來就介紹我常用的功能。  
_筆者目前 Chrome 版本為 39.0.2171.99 (64-bit); 作業系統: OS X 10.10.1_
## Device Mode

剛開始吹起 RWD 風的時候，有許多外掛、網站可以藉由調整瀏覽器大小，或是嵌入多個 iframe 以模擬各個行動裝置的螢幕大小，但是現在已經可以藉由 Chrome 內建的功能達到囉。
### Step 0: 開啟 Device Mode
1.  
   - 如果是使用 Mac 可以使用組合鍵`command + option + i`開啟面板
   - 也可以點選『漢堡選單![漢堡選單](https://cloud.githubusercontent.com/assets/4229697/5792420/54351b24-9f52-11e4-87ca-780b06b3b19c.png) / 更多工具 / 開發人員工具』
2. 接著會看到以下面的畫面  
   ![開發人員工具](https://cloud.githubusercontent.com/assets/4229697/5792516/10218864-9f57-11e4-9042-7acfb3240ee1.jpeg)
3. 點擊選單左方的手持裝置圖示![手持裝置圖示](https://cloud.githubusercontent.com/assets/4229697/5792434/1359fe48-9f53-11e4-942c-e5602b73fd68.png)，來開啟 device mode 。
4. 如果成功的話，手持裝置的圖示將會被高亮![高亮的手持裝置圖示](https://cloud.githubusercontent.com/assets/4229697/5792435/1dcf0738-9f53-11e4-8d48-28de28c08b63.png)  
   也會看到整個網站被暗色系的面板包圍  
   ![已開啟 Device Mode](https://cloud.githubusercontent.com/assets/4229697/5792506/608df7f2-9f56-11e4-8b58-5152c0763c5d.png)  
   （可參考此圖內的數字圖示，對應以下要介紹的功能）
### Step 1: 選擇裝置尺寸
1. 點擊 Device 旁的下拉選單![Device 下拉選單](https://cloud.githubusercontent.com/assets/4229697/5792449/6d165c42-9f53-11e4-958b-a3c4311dbd96.png)
2. 就可以看到許多可以參考的裝置尺寸  
   ![選擇 Device](https://cloud.githubusercontent.com/assets/4229697/5792451/821d5794-9f53-11e4-8605-014837990c39.png)  
   （筆者目前~~私心~~大多以 A 品牌的尺寸為參考依據）
3. 選擇玩尺寸之後，可以看見尺寸及 UA 的欄位也幫開發者一併填上了  
   ![尺寸、 UA 欄位](https://cloud.githubusercontent.com/assets/4229697/5792465/8edd7e4a-9f54-11e4-8fbd-49489397681a.png)  
   真的是揪甘心der
4. 然後最重要的是，調整完裝置的設定之後，一定要重新 **refresh** ，這樣網站的樣式才會套用新的設定  
   ![重新 refresh 提示](https://cloud.githubusercontent.com/assets/4229697/5792470/9cb0bc8a-9f54-11e4-9448-63f85e13b322.png)
### Step 2: 選擇網路速度
1. 點擊 Network 旁的下拉選單![Network 下拉選單](https://cloud.githubusercontent.com/assets/4229697/5792472/a8ecc35e-9f54-11e4-98b6-1c0759b38dc9.png)
2. 就可以模擬網站在這種速度下 loading 的狀況  
   ![選擇 Network](https://cloud.githubusercontent.com/assets/4229697/5792476/c986970c-9f54-11e4-9dfa-f28fa9e3da28.png)  
   _但實際的網路情況並不會如此的穩定連接，可能時好時壞，所以真的僅供參考_
### Step3: 縮放至適當大小

有時候在模擬裝置螢幕大小的時候，難免因為已經開啟了開發人員工具，又或是因為 PC / 筆電的螢幕不夠大，無法瀏覽整個網站的情況，這時候就可以使用這個功能。
1. 勾選 Fit![縮放至適當大小](https://cloud.githubusercontent.com/assets/4229697/5792478/d4d943b6-9f54-11e4-8d71-61fbb537064e.png)
2. 比較圖  
   ![縮放前後比較圖](https://cloud.githubusercontent.com/assets/4229697/5792481/dfdf107e-9f54-11e4-8392-f1683891fef2.png)
### Step4: 重置覆寫的設定
1. 如果要關閉因開啟 Device Mode 所異動的設定，可以直接點擊禁止符號![Reset All Overrides](https://cloud.githubusercontent.com/assets/4229697/5792483/ef9f8188-9f54-11e4-98a2-e7dca04abbf4.png)，就可以重置設定 (Device, Network, Screen Size, Pixel Ratio, UA)
2. 重置之後，同樣也需要 **refresh**
### Step5: 檢索 Media Queries
- 這個功能挺有趣的，他可以將網站所使用 Media Queries 涵蓋的螢幕尺寸列出，可用這個方式去觀察其它網站是怎麼規劃各個螢幕尺寸的設計。
  1. 點選像似階梯的符號![Media Queries Found](https://cloud.githubusercontent.com/assets/4229697/5792485/fc00ebe2-9f54-11e4-8967-585eeb374824.png)
  2. 接著會看到多個不同顏色的條狀圖拼接著  
     ![Media Queries Found](https://cloud.githubusercontent.com/assets/4229697/5792487/07c60728-9f55-11e4-89d2-0749fada4e17.png)
  3. 如果將滑鼠暫作停留，可以看出 media query 的設定值  
     ![Hover Media Queries Bar](https://cloud.githubusercontent.com/assets/4229697/5792493/400e1030-9f55-11e4-8889-38f729293499.png)
  4. 如果直接點擊條狀圖，整個顯示區域的寬度就會被調整為 media query 的設定的值  
     ![Hover Click Queries Bar](https://cloud.githubusercontent.com/assets/4229697/5792496/4e4a776a-9f55-11e4-9a3b-7c3d8f86e9a3.png)
- 若是在開發時，有時候還不確定 media query 設定的界限，可利用以下方式去觀察網頁是否有破版，或是待調整的地方。
  1. 勾選修改畫面尺寸的 CheckBox ，接著直接修改數值  
     ![Emulate Screen Resolution](https://cloud.githubusercontent.com/assets/4229697/5792497/5bd4b36e-9f55-11e4-8635-32d23f565547.png)
  2. 拖曳右側或下方的 Bar ，直接修改寬高  
     ![Screen Bar](https://cloud.githubusercontent.com/assets/4229697/5792498/69b62ce2-9f55-11e4-9402-0dd43f102f5e.png)
## 結語

相信學會了這幾招，在開發 RWD 的時候，應該就更能得心應手了。有機會再介紹其它 Chrome 好用的功能

**影像擷取出處來源：www.dadaabstories.org, Google Chrome**

**Comment by DerekHung** [comment]
非常感謝您的投稿！在近日內會公布此次徵稿活動的結果，敬請期待:D
